name: taskapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  ionicons: 0.2.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: 6.2.1
  cloud_firestore: 4.13.6
  date_time_picker: 2.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

